language: python
python:
    - "3.5"
install:
    - "pip install -r requirements-test.txt"
    - "pip install python-coveralls"
    - "pip install -e ."
script:
    - "py.test -v --cov=asyncio_apns"
after_success:
    - "coveralls"